const D=window.COCKPIT_PUBLIC,P=D.programs,Q=D.research_queue,K=D.karl,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=x=>String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function show(id){$$(".view").forEach(x=>x.classList.remove("on"));$("#"+id).classList.add("on");$$(".tabs button").forEach(x=>x.classList.toggle("on",x.dataset.v===id))}
$$(".tabs button").forEach(b=>b.onclick=()=>show(b.dataset.v));
$("#nprog").textContent=P.length;$("#nqueue").textContent=Q.length;$("#nkarl").textContent=K.claims.filter(x=>x.priority_code==="P0").length;$("#nhold").textContent=K.holds.length;
const fam=[...new Set(P.map(x=>x.family).filter(Boolean))].sort();$("#fam").innerHTML='<option value="">Toutes familles</option>'+fam.map(x=>`<option>${esc(x)}</option>`).join("");
function render(){let q=$("#q").value.toLowerCase(),f=$("#fam").value,a=P.filter(p=>(!f||p.family===f)&&(!q||JSON.stringify(p).toLowerCase().includes(q)));$("#count").textContent=`${a.length} / ${P.length}`;$("#books").innerHTML=a.map(p=>`<div class="card book" data-id="${p.id}"><span class="badge">${esc(p.family)}</span><h3>${esc(p.name)}</h3><div class="muted">${esc(p.function)} · ${esc(p.dates)}</div><p>${esc(p.current_research?.status||p.research_status_legacy)}</p></div>`).join("");$$(".book").forEach(b=>b.onclick=()=>openP(+b.dataset.id))}
$("#q").oninput=render;$("#fam").onchange=render;render();
function openP(id){let p=P.find(x=>x.id===id);let extra="";if(id===93){extra=`<h2>Claims Karl</h2>${K.claims.map(c=>`<div class="card" style="margin:10px 0"><b>${esc(c.local_id)} — ${esc(c.title||c.question||"")}</b><p>${esc(c.conclusion||"")}</p><span class="badge bad">${esc(c.sensitivity_code||c.sensitivity||"")}</span> <span class="badge">${esc(c.depth_code||c.depth||"")}</span></div>`).join("")}<h2>HOLD Karl</h2><div class="card table"><table><tr><th>ID</th><th>Disposition</th><th>PRG</th><th>Raison</th></tr>${K.holds.map(h=>`<tr><td>${esc(h.id)}</td><td>${esc(h.disposition_code)}</td><td>${esc(h.prg_code)}</td><td>${esc(h.reason)}</td></tr>`).join("")}</table></div>`}$("#detail").innerHTML=`<button class="back">← bibliothèque</button><h2>${esc(p.name)}</h2><p class="muted">${esc(p.family)} · ${esc(p.dates)}</p><div class="card"><b>${esc(p.function)}</b><p>Legacy : ${esc(p.research_status_legacy)} · maturité ${esc(p.maturity_legacy)}</p>${p.current_research?`<p><span class="badge good">${esc(p.current_research.status)}</span></p>`:""}</div>${extra}`;$("#detail .back").onclick=()=>show("library");show("detail")}
$("#queue").innerHTML=Q.map(x=>`<tr><td>${esc(x.order)}</td><td><b>${esc(x.program)}</b></td><td>${esc(x.state)}</td><td>${esc(x.question)}</td></tr>`).join("");show("home");